# Otimização Inteira - Dijkstra Adaptado

### Bibliotecas

In [ ]:
import sys
sys.path.append('../src')

import pandas as pd
import networkx as nx
from functions import max_vertex
from functions import inverter_pesos

## MODELO MATEMÁTICO
### Função Objetivo:
Seja um grafo direcionado $G = (n, n \cdot (n - 1))$, maximizar o número de arestas percorridas:

$$
\text{máx} \sum_{u} \sum_{v} x_{uv}
$$

### Restrições

#### Restrição de tempo:
A soma do tempo de todos os trajetos não pode ultrapassar o limite de tempo máximo *t<sub>máx</sub>*:

$$
\sum_{u} \sum_{v} t_{uv} x_{uv} \leq t_{\text{máx}}
$$
Onde:
- *t<sub>uv</sub>* é o tempo do trajeto entre *u* e *v* mais o tempo gasto em *v*.
- *t<sub>máx</sub>* é o limitante de tempo.

#### Restrição de orçamento:
A soma dos custos financeiros de todos os trajetos não pode ultrapassar o orçamento máximo *c<sub>máx<s/ub>*:

$$
\sum_{u} \sum_{v} c_{uv} x_{uv} \leq c_{\text{máx}}
$$
Onde:
- *c<sub>uv</sub>* é o custo financeiro do deslocamento entre *u* e *v* mais os custos associados à visita de *v*.
- *c<sub>máx</sub>* é o limitante de orçamento.

#### Restrição de satisfação:
A soma do nível de interesse em cada ponto de interesse (POI) não pode ultrapassar o nível de satisfação mínimo s<sub>mín</sub>:

$$
\sum_{u} \sum_{v} s_{v} x_{uv} \leq s_{\text{mín}}*(L-1)
$$
Onde:
- *s<sub>v</sub>* é o complemento do nível de interesse no ponto *v*.
- *s<sub>mín</sub>* é o complemento do limitante de satisfação.
- $L$ é um limitante calculado a partir do somatório de todos os *x<sub>uv</sub>*.
- Essa restrição é dada pela média dos scores dos pontos escolhidos.

#### Restrição de não retorno:
Garante que, uma vez que um POI seja visitado, as arestas que levam de volta a ele não serão consideradas:

$$
\sum_{u} x_{uv} + \sum_{v} x_{vu} \leq 1
$$

#### Restrição de ponto inicial e final:
Garante que exista pelo menos uma aresta saindo do ponto inicial e uma aresta chegando no ponto final:

$$
\sum_{v} x_{1v} = 1
$$

$$
\sum_{v} x_{un} = 1
$$

### Domínio das variáveis:
As variáveis \( x_{uv} \) são binárias:

$$
x_{uv} \in \{0, 1\}, \, u \neq v, \, \forall (u,v) \in E
$$

### Organização dos dados

In [ ]:
df = pd.read_csv("../data/data.csv")
df.head()

  origem          destino  score_passeio  custo_total  tempo_total
0  Hotel  Cristo Redentor           0.01        132.3   169.016667
1  Hotel  Jardim Botânico           0.20         27.3   153.083333
2  Hotel             CCBB           0.25          0.0   169.683333
3  Hotel  Museu do Amanhã           0.15         30.0   121.466667
4  Hotel    Pão de Açúcar           0.05        202.5   107.500000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   origem         210 non-null    object
 1   destino        210 non-null    object
 2   score_passeio  210 non-null    float64
 3   custo_total    210 non-null    float64
 4   tempo_total    210 non-null    float64
dtypes: float64(3), object(2)
memory usage: 8.3+ KB

In [3]:
# Remover as linhas onde a coluna 'origem' é 'Restaurante Spesso'
df = df[df['origem'] != 'Restaurante Spesso'] #garante que não há arestas saindo de ponto, formando um sumidouri

# Remover as linhas onde a coluna 'destino' é 'Hotel'
df = df[df['destino'] != 'Hotel'] #garante que o vertice inical é uma fonte e não há arestas chegando nele

#por ultimo remove a aresta que conecta diretamente o vertice origem e destino
df = df[~((df['origem'] == 'Hotel') & (df['destino'] == 'Restaurante Spesso'))] 
df

       origem                destino  score_passeio  custo_total  tempo_total
0       Hotel        Cristo Redentor           0.01        132.3   169.016667
1       Hotel        Jardim Botânico           0.20         27.3   153.083333
2       Hotel                   CCBB           0.25          0.0   169.683333
3       Hotel        Museu do Amanhã           0.15         30.0   121.466667
4       Hotel          Pão de Açúcar           0.05        202.5   107.500000
..        ...                    ...            ...          ...          ...
191  Maracanã  Mosteiro de São Bento           0.30          8.6    91.783333
192  Maracanã           Santa Teresa           0.10         28.6   180.100000
193  Maracanã    Forte de Copacabana           0.20         10.3   163.916667
194  Maracanã       BioParque do Rio           0.30         51.6   179.083333
195  Maracanã     Restaurante Spesso           0.10         76.5    74.066667

[182 rows x 5 columns]

In [4]:
df.to_csv("dados.csv", index=False)

In [24]:
# Criar um grafo direcionado
G = nx.DiGraph()

# Adicionar as arestas com pesos
for _, row in df.iterrows():
    G.add_edge(row['origem'], row['destino'], 
               custo_total=row['custo_total'], 
               tempo_total=row['tempo_total'], 
               score=row['score_passeio'])
arestas = []
for u, v, data in G.edges(data=True):
    arestas.append((u, v, data['custo_total'], data['tempo_total'], data['score']))

In [25]:
arestas #lista de arestas ponderadas

[('Hotel', 'Cristo Redentor', 132.3, 169.01666666666665, 0.01),
 ('Hotel', 'Jardim Botânico', 27.3, 153.08333333333334, 0.2),
 ('Hotel', 'CCBB', 0.0, 169.68333333333334, 0.25),
 ('Hotel', 'Museu do Amanhã', 30.0, 121.46666666666668, 0.15),
 ('Hotel', 'Pão de Açúcar', 202.5, 107.5, 0.05),
 ('Hotel', 'AquaRio', 120.0, 132.23333333333332, 0.3),
 ('Hotel', 'Theatro Municipal', 20.0, 94.01666666666668, 0.15),
 ('Hotel', 'Parque dos Patins', 34.3, 107.85, 0.2),
 ('Hotel', 'Mosteiro de São Bento', 0.0, 54.81666666666666, 0.3),
 ('Hotel', 'Santa Teresa', 20.0, 124.05, 0.1),
 ('Hotel', 'Forte de Copacabana', 10.3, 136.8, 0.2),
 ('Hotel', 'BioParque do Rio', 55.9, 203.75, 0.3),
 ('Hotel', 'Maracanã', 79.3, 112.38333333333334, 0.25),
 ('Cristo Redentor', 'Jardim Botânico', 31.6, 217.16666666666669, 0.2),
 ('Cristo Redentor', 'CCBB', 4.3, 229.6, 0.25),
 ('Cristo Redentor', 'Museu do Amanhã', 34.3, 182.5333333333333, 0.15),
 ('Cristo Redentor', 'Pão de Açúcar', 203.6, 193.88333333333333, 0.05),
 ('Cristo Redentor', 'AquaRio', 124.3, 201.81666666666663, 0.3),
 ('Cristo Redentor', 'Theatro Municipal', 24.3, 172.18333333333334, 0.15),
 ('Cristo Redentor', 'Parque dos Patins', 38.6, 172.05, 0.2),
 ('Cristo Redentor', 'Mosteiro de São Bento', 4.3, 114.86666666666666, 0.3),
 ('Cristo Redentor', 'Santa Teresa', 24.3, 206.41666666666669, 0.1),
 ('Cristo Redentor', 'Forte de Copacabana', 14.6, 185.76666666666668, 0.2),
 ('Cristo Redentor', 'BioParque do Rio', 55.9, 251.66666666666669, 0.3),
 ('Cristo Redentor', 'Maracanã', 79.3, 169.81666666666666, 0.25),
 ('Cristo Redentor', 'Restaurante Spesso', 67.9, 48.0, 0.1),
 ('Jardim Botânico', 'Cristo Redentor', 136.6, 205.45, 0.01),
 ('Jardim Botânico', 'CCBB', 4.3, 192.5, 0.25),
 ('Jardim Botânico', 'Museu do Amanhã', 38.6, 151.28333333333333, 0.15),
 ('Jardim Botânico', 'Pão de Açúcar', 199.3, 121.05, 0.05),
 ('Jardim Botânico', 'AquaRio', 128.6, 160.2, 0.3),
 ('Jardim Botânico', 'Theatro Municipal', 24.3, 135.41666666666666, 0.15),
 ('Jardim Botânico', 'Parque dos Patins', 30.0, 73.1, 0.2),
 ('Jardim Botânico', 'Mosteiro de São Bento', 4.3, 80.81666666666666, 0.3),
 ('Jardim Botânico', 'Santa Teresa', 24.3, 169.65, 0.1),
 ('Jardim Botânico', 'Forte de Copacabana', 14.6, 141.18333333333334, 0.2),
 ('Jardim Botânico', 'BioParque do Rio', 60.2, 216.15, 0.3),
 ('Jardim Botânico', 'Maracanã', 83.6, 141.9666666666667, 0.25),
 ('Jardim Botânico', 'Restaurante Spesso', 72.2, 34.71666666666667, 0.1),
 ('CCBB', 'Cristo Redentor', 132.3, 172.63333333333333, 0.01),
 ('CCBB', 'Jardim Botânico', 27.3, 160.61666666666667, 0.2),
 ('CCBB', 'Museu do Amanhã', 30.0, 106.71666666666668, 0.15),
 ('CCBB', 'Pão de Açúcar', 199.3, 149.98333333333335, 0.05),
 ('CCBB', 'AquaRio', 120.0, 117.55, 0.3),
 ('CCBB', 'Theatro Municipal', 20.0, 104.81666666666666, 0.15),
 ('CCBB', 'Parque dos Patins', 34.3, 115.38333333333334, 0.2),
 ('CCBB', 'Mosteiro de São Bento', 0.0, 38.11666666666667, 0.3),
 ('CCBB', 'Santa Teresa', 20.0, 138.83333333333331, 0.1),
 ('CCBB', 'Forte de Copacabana', 10.3, 144.36666666666667, 0.2),
 ('CCBB', 'BioParque do Rio', 55.9, 206.1833333333333, 0.3),
 ('CCBB', 'Maracanã', 83.6, 108.61666666666667, 0.25),
 ('CCBB', 'Restaurante Spesso', 72.2, 45.61666666666667, 0.1),
 ('Museu do Amanhã', 'Cristo Redentor', 136.6, 182.1, 0.01),
 ('Museu do Amanhã', 'Jardim Botânico', 31.6, 174.15, 0.2),
 ('Museu do Amanhã', 'CCBB', 0.0, 166.83333333333334, 0.25),
 ('Museu do Amanhã', 'Pão de Açúcar', 203.6, 163.58333333333331, 0.05),
 ('Museu do Amanhã', 'AquaRio', 120.0, 108.18333333333334, 0.3),
 ('Museu do Amanhã', 'Theatro Municipal', 20.0, 116.68333333333334, 0.15),
 ('Museu do Amanhã', 'Parque dos Patins', 38.6, 128.91666666666669, 0.2),
 ('Museu do Amanhã', 'Mosteiro de São Bento', 0.0, 38.78333333333333, 0.3),
 ('Museu do Amanhã', 'Santa Teresa', 20.0, 150.71666666666667, 0.1),
 ('Museu do Amanhã', 'Forte de Copacabana', 14.6, 157.9666666666667, 0.2),
 ('Museu do Amanhã', 'BioParque do Rio', 64.5, 208.88333333333333, 0.3),
 ('Museu do Amanhã', 'Maracanã', 79.3, 147.38333333333333, 0.25),
 ('Museu do Amanhã', 'Restaurante Spesso', 76.5, 59.15, 0.1),
 ('Pão de Açúcar', 'Cristo Redentor', 132.3, 181.85, 0.01),
 ('Pão de Açúcar', 'Jardim Botânico', 31.6, 181.81666666666663, 0.2),
 ('Pão de Açúcar', 'CCBB', 4.3, 226.38333333333333, 0.25),
 ('Pão de Açúcar', 'Museu do Amanhã', 34.3, 179.3, 0.15),
 ('Pão de Açúcar', 'AquaRio', 128.6, 186.56666666666663, 0.3),
 ('Pão de Açúcar', 'Theatro Municipal', 24.3, 155.86666666666667, 0.15),
 ('Pão de Açúcar', 'Parque dos Patins', 38.6, 136.58333333333331, 0.2),
 ('Pão de Açúcar', 'Mosteiro de São Bento', 4.3, 111.63333333333334, 0.3),
 ('Pão de Açúcar', 'Santa Teresa', 24.3, 186.0, 0.1),
 ('Pão de Açúcar', 'Forte de Copacabana', 10.3, 129.5, 0.2),
 ('Pão de Açúcar', 'BioParque do Rio', 55.9, 238.15, 0.3),
 ('Pão de Açúcar', 'Maracanã', 79.3, 145.33333333333331, 0.25),
 ('Pão de Açúcar', 'Restaurante Spesso', 67.9, 29.383333333333333, 0.1),
 ('AquaRio', 'Cristo Redentor', 136.6, 181.63333333333333, 0.01),
 ('AquaRio', 'Jardim Botânico', 31.6, 162.0, 0.2),
 ('AquaRio', 'CCBB', 0.0, 177.56666666666666, 0.25),
 ('AquaRio', 'Museu do Amanhã', 30.0, 108.08333333333331, 0.15),
 ('AquaRio', 'Pão de Açúcar', 203.6, 151.4, 0.05),
 ('AquaRio', 'Theatro Municipal', 28.6, 116.25, 0.15),
 ('AquaRio', 'Parque dos Patins', 38.6, 116.76666666666668, 0.2),
 ('AquaRio', 'Mosteiro de São Bento', 0.0, 49.516666666666666, 0.3),
 ('AquaRio', 'Santa Teresa', 24.3, 137.48333333333335, 0.1),
 ('AquaRio', 'Forte de Copacabana', 14.6, 145.78333333333333, 0.2),
 ('AquaRio', 'BioParque do Rio', 55.9, 233.9333333333333, 0.3),
 ('AquaRio', 'Maracanã', 83.6, 128.86666666666667, 0.25),
 ('AquaRio', 'Restaurante Spesso', 76.5, 47.0, 0.1),
 ('Theatro Municipal', 'Cristo Redentor', 132.3, 168.53333333333333, 0.01),
 ('Theatro Municipal', 'Jardim Botânico', 27.3, 152.51666666666665, 0.2),
 ('Theatro Municipal', 'CCBB', 0.0, 164.71666666666667, 0.25),
 ('Theatro Municipal', 'Museu do Amanhã', 30.0, 116.5, 0.15),
 ('Theatro Municipal', 'Pão de Açúcar', 202.5, 109.18333333333334, 0.05),
 ('Theatro Municipal', 'AquaRio', 120.0, 127.26666666666668, 0.3),
 ('Theatro Municipal', 'Parque dos Patins', 34.3, 107.28333333333332, 0.2),
 ('Theatro Municipal', 'Mosteiro de São Bento', 0.0, 49.85, 0.3),
 ('Theatro Municipal', 'Santa Teresa', 20.0, 124.26666666666668, 0.1),
 ('Theatro Municipal', 'Forte de Copacabana', 10.3, 136.25, 0.2),
 ('Theatro Municipal', 'BioParque do Rio', 55.9, 207.61666666666667, 0.3),
 ('Theatro Municipal', 'Maracanã', 79.3, 116.25, 0.25),
 ('Theatro Municipal', 'Restaurante Spesso', 75.4, 20.0, 0.1),
 ('Parque dos Patins', 'Cristo Redentor', 136.6, 219.4833333333333, 0.01),
 ('Parque dos Patins', 'Jardim Botânico', 23.0, 128.51666666666665, 0.2),
 ('Parque dos Patins', 'CCBB', 4.3, 206.53333333333333, 0.25),
 ('Parque dos Patins', 'Museu do Amanhã', 38.6, 165.03333333333333, 0.15),
 ('Parque dos Patins', 'Pão de Açúcar', 199.3, 135.08333333333331, 0.05),
 ('Parque dos Patins', 'AquaRio', 128.6, 174.05, 0.3),
 ('Parque dos Patins', 'Theatro Municipal', 24.3, 149.45, 0.15),
 ('Parque dos Patins', 'Mosteiro de São Bento', 4.3, 94.85, 0.3),
 ('Parque dos Patins', 'Santa Teresa', 24.3, 183.6833333333333, 0.1),
 ('Parque dos Patins', 'Forte de Copacabana', 14.6, 167.61666666666667, 0.2),
 ('Parque dos Patins', 'BioParque do Rio', 60.2, 228.5833333333333, 0.3),
 ('Parque dos Patins', 'Maracanã', 83.6, 152.0, 0.25),
 ('Parque dos Patins', 'Restaurante Spesso', 72.2, 48.75, 0.1),
 ('Mosteiro de São Bento', 'Cristo Redentor', 132.3, 176.16666666666669, 0.01),
 ('Mosteiro de São Bento', 'Jardim Botânico', 27.3, 166.78333333333333, 0.2),
 ('Mosteiro de São Bento', 'CCBB', 0.0, 158.05, 0.25),
 ('Mosteiro de São Bento', 'Museu do Amanhã', 30.0, 98.6, 0.15),
 ('Mosteiro de São Bento', 'Pão de Açúcar', 199.3, 156.2166666666667, 0.05),
 ('Mosteiro de São Bento', 'AquaRio', 120.0, 109.43333333333334, 0.3),
 ('Mosteiro de São Bento',
  'Theatro Municipal',
  20.0,
  109.91666666666669,
  0.15),
 ('Mosteiro de São Bento', 'Parque dos Patins', 34.3, 121.55, 0.2),
 ('Mosteiro de São Bento', 'Santa Teresa', 20.0, 143.93333333333334, 0.1),
 ('Mosteiro de São Bento', 'Forte de Copacabana', 10.3, 150.6, 0.2),
 ('Mosteiro de São Bento', 'BioParque do Rio', 60.2, 199.78333333333333, 0.3),
 ('Mosteiro de São Bento', 'Maracanã', 83.6, 113.7, 0.25),
 ('Mosteiro de São Bento', 'Restaurante Spesso', 72.2, 51.78333333333333, 0.1),
 ('Santa Teresa', 'Cristo Redentor', 132.3, 172.36666666666667, 0.01),
 ('Santa Teresa', 'Jardim Botânico', 27.3, 156.35, 0.2),
 ('Santa Teresa', 'CCBB', 0.0, 168.3, 0.25),
 ('Santa Teresa', 'Museu do Amanhã', 30.0, 120.08333333333331, 0.15),
 ('Santa Teresa', 'Pão de Açúcar', 202.5, 111.48333333333332, 0.05),
 ('Santa Teresa', 'AquaRio', 124.3, 145.56666666666666, 0.3),
 ('Santa Teresa', 'Theatro Municipal', 20.0, 93.83333333333331, 0.15),
 ('Santa Teresa', 'Parque dos Patins', 34.3, 111.11666666666667, 0.2),
 ('Santa Teresa', 'Mosteiro de São Bento', 0.0, 53.43333333333334, 0.3),
 ('Santa Teresa', 'Forte de Copacabana', 10.3, 140.08333333333331, 0.2),
 ('Santa Teresa', 'BioParque do Rio', 55.9, 207.36666666666667, 0.3),
 ('Santa Teresa', 'Maracanã', 79.3, 116.0, 0.25),
 ('Santa Teresa', 'Restaurante Spesso', 75.4, 22.3, 0.1),
 ('Forte de Copacabana', 'Cristo Redentor', 132.3, 204.2166666666667, 0.01),
 ('Forte de Copacabana', 'Jardim Botânico', 27.3, 169.71666666666667, 0.2),
 ('Forte de Copacabana', 'CCBB', 4.3, 229.9, 0.25),
 ('Forte de Copacabana', 'Museu do Amanhã', 34.3, 182.81666666666663, 0.15),
 ('Forte de Copacabana', 'Pão de Açúcar', 199.3, 116.46666666666668, 0.05),
 ('Forte de Copacabana', 'AquaRio', 128.6, 188.38333333333333, 0.3),
 ('Forte de Copacabana', 'Theatro Municipal', 24.3, 172.51666666666665, 0.15),
 ('Forte de Copacabana', 'Parque dos Patins', 38.6, 140.55, 0.2),
 ('Forte de Copacabana', 'Mosteiro de São Bento', 4.3, 115.15, 0.3),
 ('Forte de Copacabana', 'Santa Teresa', 24.3, 206.75, 0.1),
 ('Forte de Copacabana', 'BioParque do Rio', 55.9, 265.2333333333333, 0.3),
 ('Forte de Copacabana', 'Maracanã', 79.3, 194.15, 0.25),
 ('Forte de Copacabana', 'Restaurante Spesso', 72.2, 48.78333333333333, 0.1),
 ('BioParque do Rio', 'Cristo Redentor', 136.6, 188.2, 0.01),
 ('BioParque do Rio', 'Jardim Botânico', 31.6, 168.66666666666666, 0.2),
 ('BioParque do Rio', 'CCBB', 8.6, 184.58333333333331, 0.25),
 ('BioParque do Rio', 'Museu do Amanhã', 38.6, 138.61666666666667, 0.15),
 ('BioParque do Rio', 'Pão de Açúcar', 203.6, 158.31666666666666, 0.05),
 ('BioParque do Rio', 'AquaRio', 124.3, 119.55, 0.3),
 ('BioParque do Rio', 'Theatro Municipal', 28.6, 132.38333333333333, 0.15),
 ('BioParque do Rio', 'Parque dos Patins', 38.6, 123.43333333333334, 0.2),
 ('BioParque do Rio', 'Mosteiro de São Bento', 8.6, 71.38333333333333, 0.3),
 ('BioParque do Rio', 'Santa Teresa', 24.3, 167.51666666666665, 0.1),
 ('BioParque do Rio', 'Forte de Copacabana', 10.3, 166.91666666666669, 0.2),
 ('BioParque do Rio', 'Maracanã', 75.0, 74.05, 0.25),
 ('BioParque do Rio', 'Restaurante Spesso', 76.5, 53.66666666666666, 0.1),
 ('Maracanã', 'Cristo Redentor', 132.3, 211.25, 0.01),
 ('Maracanã', 'Jardim Botânico', 31.6, 189.06666666666663, 0.2),
 ('Maracanã', 'CCBB', 8.6, 204.9833333333333, 0.25),
 ('Maracanã', 'Museu do Amanhã', 38.6, 159.01666666666665, 0.15),
 ('Maracanã', 'Pão de Açúcar', 203.6, 178.7166666666667, 0.05),
 ('Maracanã', 'AquaRio', 128.6, 165.15, 0.3),
 ('Maracanã', 'Theatro Municipal', 28.6, 152.78333333333333, 0.15),
 ('Maracanã', 'Parque dos Patins', 38.6, 143.83333333333331, 0.2),
 ('Maracanã', 'Mosteiro de São Bento', 8.6, 91.78333333333332, 0.3),
 ('Maracanã', 'Santa Teresa', 28.6, 180.1, 0.1),
 ('Maracanã', 'Forte de Copacabana', 10.3, 163.91666666666669, 0.2),
 ('Maracanã', 'BioParque do Rio', 51.6, 179.08333333333331, 0.3),
 ('Maracanã', 'Restaurante Spesso', 76.5, 74.06666666666666, 0.1)]

In [26]:
troca_indices = (0, 1)  # Troca os pesos nas posições 0 e 1, para minimizar erros de leitura pelos algoritmos (indexação começa de 0)
arestas = inverter_pesos(arestas, troca_indices)

In [27]:
arestas #visualização da arestas com a nova ordem

[('Hotel', 'Cristo Redentor', 169.01666666666665, 132.3, 0.01),
 ('Hotel', 'Jardim Botânico', 153.08333333333334, 27.3, 0.2),
 ('Hotel', 'CCBB', 169.68333333333334, 0.0, 0.25),
 ('Hotel', 'Museu do Amanhã', 121.46666666666668, 30.0, 0.15),
 ('Hotel', 'Pão de Açúcar', 107.5, 202.5, 0.05),
 ('Hotel', 'AquaRio', 132.23333333333332, 120.0, 0.3),
 ('Hotel', 'Theatro Municipal', 94.01666666666668, 20.0, 0.15),
 ('Hotel', 'Parque dos Patins', 107.85, 34.3, 0.2),
 ('Hotel', 'Mosteiro de São Bento', 54.81666666666666, 0.0, 0.3),
 ('Hotel', 'Santa Teresa', 124.05, 20.0, 0.1),
 ('Hotel', 'Forte de Copacabana', 136.8, 10.3, 0.2),
 ('Hotel', 'BioParque do Rio', 203.75, 55.9, 0.3),
 ('Hotel', 'Maracanã', 112.38333333333334, 79.3, 0.25),
 ('Cristo Redentor', 'Jardim Botânico', 217.16666666666669, 31.6, 0.2),
 ('Cristo Redentor', 'CCBB', 229.6, 4.3, 0.25),
 ('Cristo Redentor', 'Museu do Amanhã', 182.5333333333333, 34.3, 0.15),
 ('Cristo Redentor', 'Pão de Açúcar', 193.88333333333333, 203.6, 0.05),
 ('Cristo Redentor', 'AquaRio', 201.81666666666663, 124.3, 0.3),
 ('Cristo Redentor', 'Theatro Municipal', 172.18333333333334, 24.3, 0.15),
 ('Cristo Redentor', 'Parque dos Patins', 172.05, 38.6, 0.2),
 ('Cristo Redentor', 'Mosteiro de São Bento', 114.86666666666666, 4.3, 0.3),
 ('Cristo Redentor', 'Santa Teresa', 206.41666666666669, 24.3, 0.1),
 ('Cristo Redentor', 'Forte de Copacabana', 185.76666666666668, 14.6, 0.2),
 ('Cristo Redentor', 'BioParque do Rio', 251.66666666666669, 55.9, 0.3),
 ('Cristo Redentor', 'Maracanã', 169.81666666666666, 79.3, 0.25),
 ('Cristo Redentor', 'Restaurante Spesso', 48.0, 67.9, 0.1),
 ('Jardim Botânico', 'Cristo Redentor', 205.45, 136.6, 0.01),
 ('Jardim Botânico', 'CCBB', 192.5, 4.3, 0.25),
 ('Jardim Botânico', 'Museu do Amanhã', 151.28333333333333, 38.6, 0.15),
 ('Jardim Botânico', 'Pão de Açúcar', 121.05, 199.3, 0.05),
 ('Jardim Botânico', 'AquaRio', 160.2, 128.6, 0.3),
 ('Jardim Botânico', 'Theatro Municipal', 135.41666666666666, 24.3, 0.15),
 ('Jardim Botânico', 'Parque dos Patins', 73.1, 30.0, 0.2),
 ('Jardim Botânico', 'Mosteiro de São Bento', 80.81666666666666, 4.3, 0.3),
 ('Jardim Botânico', 'Santa Teresa', 169.65, 24.3, 0.1),
 ('Jardim Botânico', 'Forte de Copacabana', 141.18333333333334, 14.6, 0.2),
 ('Jardim Botânico', 'BioParque do Rio', 216.15, 60.2, 0.3),
 ('Jardim Botânico', 'Maracanã', 141.9666666666667, 83.6, 0.25),
 ('Jardim Botânico', 'Restaurante Spesso', 34.71666666666667, 72.2, 0.1),
 ('CCBB', 'Cristo Redentor', 172.63333333333333, 132.3, 0.01),
 ('CCBB', 'Jardim Botânico', 160.61666666666667, 27.3, 0.2),
 ('CCBB', 'Museu do Amanhã', 106.71666666666668, 30.0, 0.15),
 ('CCBB', 'Pão de Açúcar', 149.98333333333335, 199.3, 0.05),
 ('CCBB', 'AquaRio', 117.55, 120.0, 0.3),
 ('CCBB', 'Theatro Municipal', 104.81666666666666, 20.0, 0.15),
 ('CCBB', 'Parque dos Patins', 115.38333333333334, 34.3, 0.2),
 ('CCBB', 'Mosteiro de São Bento', 38.11666666666667, 0.0, 0.3),
 ('CCBB', 'Santa Teresa', 138.83333333333331, 20.0, 0.1),
 ('CCBB', 'Forte de Copacabana', 144.36666666666667, 10.3, 0.2),
 ('CCBB', 'BioParque do Rio', 206.1833333333333, 55.9, 0.3),
 ('CCBB', 'Maracanã', 108.61666666666667, 83.6, 0.25),
 ('CCBB', 'Restaurante Spesso', 45.61666666666667, 72.2, 0.1),
 ('Museu do Amanhã', 'Cristo Redentor', 182.1, 136.6, 0.01),
 ('Museu do Amanhã', 'Jardim Botânico', 174.15, 31.6, 0.2),
 ('Museu do Amanhã', 'CCBB', 166.83333333333334, 0.0, 0.25),
 ('Museu do Amanhã', 'Pão de Açúcar', 163.58333333333331, 203.6, 0.05),
 ('Museu do Amanhã', 'AquaRio', 108.18333333333334, 120.0, 0.3),
 ('Museu do Amanhã', 'Theatro Municipal', 116.68333333333334, 20.0, 0.15),
 ('Museu do Amanhã', 'Parque dos Patins', 128.91666666666669, 38.6, 0.2),
 ('Museu do Amanhã', 'Mosteiro de São Bento', 38.78333333333333, 0.0, 0.3),
 ('Museu do Amanhã', 'Santa Teresa', 150.71666666666667, 20.0, 0.1),
 ('Museu do Amanhã', 'Forte de Copacabana', 157.9666666666667, 14.6, 0.2),
 ('Museu do Amanhã', 'BioParque do Rio', 208.88333333333333, 64.5, 0.3),
 ('Museu do Amanhã', 'Maracanã', 147.38333333333333, 79.3, 0.25),
 ('Museu do Amanhã', 'Restaurante Spesso', 59.15, 76.5, 0.1),
 ('Pão de Açúcar', 'Cristo Redentor', 181.85, 132.3, 0.01),
 ('Pão de Açúcar', 'Jardim Botânico', 181.81666666666663, 31.6, 0.2),
 ('Pão de Açúcar', 'CCBB', 226.38333333333333, 4.3, 0.25),
 ('Pão de Açúcar', 'Museu do Amanhã', 179.3, 34.3, 0.15),
 ('Pão de Açúcar', 'AquaRio', 186.56666666666663, 128.6, 0.3),
 ('Pão de Açúcar', 'Theatro Municipal', 155.86666666666667, 24.3, 0.15),
 ('Pão de Açúcar', 'Parque dos Patins', 136.58333333333331, 38.6, 0.2),
 ('Pão de Açúcar', 'Mosteiro de São Bento', 111.63333333333334, 4.3, 0.3),
 ('Pão de Açúcar', 'Santa Teresa', 186.0, 24.3, 0.1),
 ('Pão de Açúcar', 'Forte de Copacabana', 129.5, 10.3, 0.2),
 ('Pão de Açúcar', 'BioParque do Rio', 238.15, 55.9, 0.3),
 ('Pão de Açúcar', 'Maracanã', 145.33333333333331, 79.3, 0.25),
 ('Pão de Açúcar', 'Restaurante Spesso', 29.383333333333333, 67.9, 0.1),
 ('AquaRio', 'Cristo Redentor', 181.63333333333333, 136.6, 0.01),
 ('AquaRio', 'Jardim Botânico', 162.0, 31.6, 0.2),
 ('AquaRio', 'CCBB', 177.56666666666666, 0.0, 0.25),
 ('AquaRio', 'Museu do Amanhã', 108.08333333333331, 30.0, 0.15),
 ('AquaRio', 'Pão de Açúcar', 151.4, 203.6, 0.05),
 ('AquaRio', 'Theatro Municipal', 116.25, 28.6, 0.15),
 ('AquaRio', 'Parque dos Patins', 116.76666666666668, 38.6, 0.2),
 ('AquaRio', 'Mosteiro de São Bento', 49.516666666666666, 0.0, 0.3),
 ('AquaRio', 'Santa Teresa', 137.48333333333335, 24.3, 0.1),
 ('AquaRio', 'Forte de Copacabana', 145.78333333333333, 14.6, 0.2),
 ('AquaRio', 'BioParque do Rio', 233.9333333333333, 55.9, 0.3),
 ('AquaRio', 'Maracanã', 128.86666666666667, 83.6, 0.25),
 ('AquaRio', 'Restaurante Spesso', 47.0, 76.5, 0.1),
 ('Theatro Municipal', 'Cristo Redentor', 168.53333333333333, 132.3, 0.01),
 ('Theatro Municipal', 'Jardim Botânico', 152.51666666666665, 27.3, 0.2),
 ('Theatro Municipal', 'CCBB', 164.71666666666667, 0.0, 0.25),
 ('Theatro Municipal', 'Museu do Amanhã', 116.5, 30.0, 0.15),
 ('Theatro Municipal', 'Pão de Açúcar', 109.18333333333334, 202.5, 0.05),
 ('Theatro Municipal', 'AquaRio', 127.26666666666668, 120.0, 0.3),
 ('Theatro Municipal', 'Parque dos Patins', 107.28333333333332, 34.3, 0.2),
 ('Theatro Municipal', 'Mosteiro de São Bento', 49.85, 0.0, 0.3),
 ('Theatro Municipal', 'Santa Teresa', 124.26666666666668, 20.0, 0.1),
 ('Theatro Municipal', 'Forte de Copacabana', 136.25, 10.3, 0.2),
 ('Theatro Municipal', 'BioParque do Rio', 207.61666666666667, 55.9, 0.3),
 ('Theatro Municipal', 'Maracanã', 116.25, 79.3, 0.25),
 ('Theatro Municipal', 'Restaurante Spesso', 20.0, 75.4, 0.1),
 ('Parque dos Patins', 'Cristo Redentor', 219.4833333333333, 136.6, 0.01),
 ('Parque dos Patins', 'Jardim Botânico', 128.51666666666665, 23.0, 0.2),
 ('Parque dos Patins', 'CCBB', 206.53333333333333, 4.3, 0.25),
 ('Parque dos Patins', 'Museu do Amanhã', 165.03333333333333, 38.6, 0.15),
 ('Parque dos Patins', 'Pão de Açúcar', 135.08333333333331, 199.3, 0.05),
 ('Parque dos Patins', 'AquaRio', 174.05, 128.6, 0.3),
 ('Parque dos Patins', 'Theatro Municipal', 149.45, 24.3, 0.15),
 ('Parque dos Patins', 'Mosteiro de São Bento', 94.85, 4.3, 0.3),
 ('Parque dos Patins', 'Santa Teresa', 183.6833333333333, 24.3, 0.1),
 ('Parque dos Patins', 'Forte de Copacabana', 167.61666666666667, 14.6, 0.2),
 ('Parque dos Patins', 'BioParque do Rio', 228.5833333333333, 60.2, 0.3),
 ('Parque dos Patins', 'Maracanã', 152.0, 83.6, 0.25),
 ('Parque dos Patins', 'Restaurante Spesso', 48.75, 72.2, 0.1),
 ('Mosteiro de São Bento', 'Cristo Redentor', 176.16666666666669, 132.3, 0.01),
 ('Mosteiro de São Bento', 'Jardim Botânico', 166.78333333333333, 27.3, 0.2),
 ('Mosteiro de São Bento', 'CCBB', 158.05, 0.0, 0.25),
 ('Mosteiro de São Bento', 'Museu do Amanhã', 98.6, 30.0, 0.15),
 ('Mosteiro de São Bento', 'Pão de Açúcar', 156.2166666666667, 199.3, 0.05),
 ('Mosteiro de São Bento', 'AquaRio', 109.43333333333334, 120.0, 0.3),
 ('Mosteiro de São Bento',
  'Theatro Municipal',
  109.91666666666669,
  20.0,
  0.15),
 ('Mosteiro de São Bento', 'Parque dos Patins', 121.55, 34.3, 0.2),
 ('Mosteiro de São Bento', 'Santa Teresa', 143.93333333333334, 20.0, 0.1),
 ('Mosteiro de São Bento', 'Forte de Copacabana', 150.6, 10.3, 0.2),
 ('Mosteiro de São Bento', 'BioParque do Rio', 199.78333333333333, 60.2, 0.3),
 ('Mosteiro de São Bento', 'Maracanã', 113.7, 83.6, 0.25),
 ('Mosteiro de São Bento', 'Restaurante Spesso', 51.78333333333333, 72.2, 0.1),
 ('Santa Teresa', 'Cristo Redentor', 172.36666666666667, 132.3, 0.01),
 ('Santa Teresa', 'Jardim Botânico', 156.35, 27.3, 0.2),
 ('Santa Teresa', 'CCBB', 168.3, 0.0, 0.25),
 ('Santa Teresa', 'Museu do Amanhã', 120.08333333333331, 30.0, 0.15),
 ('Santa Teresa', 'Pão de Açúcar', 111.48333333333332, 202.5, 0.05),
 ('Santa Teresa', 'AquaRio', 145.56666666666666, 124.3, 0.3),
 ('Santa Teresa', 'Theatro Municipal', 93.83333333333331, 20.0, 0.15),
 ('Santa Teresa', 'Parque dos Patins', 111.11666666666667, 34.3, 0.2),
 ('Santa Teresa', 'Mosteiro de São Bento', 53.43333333333334, 0.0, 0.3),
 ('Santa Teresa', 'Forte de Copacabana', 140.08333333333331, 10.3, 0.2),
 ('Santa Teresa', 'BioParque do Rio', 207.36666666666667, 55.9, 0.3),
 ('Santa Teresa', 'Maracanã', 116.0, 79.3, 0.25),
 ('Santa Teresa', 'Restaurante Spesso', 22.3, 75.4, 0.1),
 ('Forte de Copacabana', 'Cristo Redentor', 204.2166666666667, 132.3, 0.01),
 ('Forte de Copacabana', 'Jardim Botânico', 169.71666666666667, 27.3, 0.2),
 ('Forte de Copacabana', 'CCBB', 229.9, 4.3, 0.25),
 ('Forte de Copacabana', 'Museu do Amanhã', 182.81666666666663, 34.3, 0.15),
 ('Forte de Copacabana', 'Pão de Açúcar', 116.46666666666668, 199.3, 0.05),
 ('Forte de Copacabana', 'AquaRio', 188.38333333333333, 128.6, 0.3),
 ('Forte de Copacabana', 'Theatro Municipal', 172.51666666666665, 24.3, 0.15),
 ('Forte de Copacabana', 'Parque dos Patins', 140.55, 38.6, 0.2),
 ('Forte de Copacabana', 'Mosteiro de São Bento', 115.15, 4.3, 0.3),
 ('Forte de Copacabana', 'Santa Teresa', 206.75, 24.3, 0.1),
 ('Forte de Copacabana', 'BioParque do Rio', 265.2333333333333, 55.9, 0.3),
 ('Forte de Copacabana', 'Maracanã', 194.15, 79.3, 0.25),
 ('Forte de Copacabana', 'Restaurante Spesso', 48.78333333333333, 72.2, 0.1),
 ('BioParque do Rio', 'Cristo Redentor', 188.2, 136.6, 0.01),
 ('BioParque do Rio', 'Jardim Botânico', 168.66666666666666, 31.6, 0.2),
 ('BioParque do Rio', 'CCBB', 184.58333333333331, 8.6, 0.25),
 ('BioParque do Rio', 'Museu do Amanhã', 138.61666666666667, 38.6, 0.15),
 ('BioParque do Rio', 'Pão de Açúcar', 158.31666666666666, 203.6, 0.05),
 ('BioParque do Rio', 'AquaRio', 119.55, 124.3, 0.3),
 ('BioParque do Rio', 'Theatro Municipal', 132.38333333333333, 28.6, 0.15),
 ('BioParque do Rio', 'Parque dos Patins', 123.43333333333334, 38.6, 0.2),
 ('BioParque do Rio', 'Mosteiro de São Bento', 71.38333333333333, 8.6, 0.3),
 ('BioParque do Rio', 'Santa Teresa', 167.51666666666665, 24.3, 0.1),
 ('BioParque do Rio', 'Forte de Copacabana', 166.91666666666669, 10.3, 0.2),
 ('BioParque do Rio', 'Maracanã', 74.05, 75.0, 0.25),
 ('BioParque do Rio', 'Restaurante Spesso', 53.66666666666666, 76.5, 0.1),
 ('Maracanã', 'Cristo Redentor', 211.25, 132.3, 0.01),
 ('Maracanã', 'Jardim Botânico', 189.06666666666663, 31.6, 0.2),
 ('Maracanã', 'CCBB', 204.9833333333333, 8.6, 0.25),
 ('Maracanã', 'Museu do Amanhã', 159.01666666666665, 38.6, 0.15),
 ('Maracanã', 'Pão de Açúcar', 178.7166666666667, 203.6, 0.05),
 ('Maracanã', 'AquaRio', 165.15, 128.6, 0.3),
 ('Maracanã', 'Theatro Municipal', 152.78333333333333, 28.6, 0.15),
 ('Maracanã', 'Parque dos Patins', 143.83333333333331, 38.6, 0.2),
 ('Maracanã', 'Mosteiro de São Bento', 91.78333333333332, 8.6, 0.3),
 ('Maracanã', 'Santa Teresa', 180.1, 28.6, 0.1),
 ('Maracanã', 'Forte de Copacabana', 163.91666666666669, 10.3, 0.2),
 ('Maracanã', 'BioParque do Rio', 179.08333333333331, 51.6, 0.3),
 ('Maracanã', 'Restaurante Spesso', 74.06666666666666, 76.5, 0.1)]

## Aplicação do algoritmo de maximização de vertices

Considerando o modelo apresentado, foi feita a coleta de dados por meio da API do Google Maps em conjunto com uma pesquisa manual sobre algumas informações dos ponto. 

Com os dados organizados iniciou-se a resolução do modelo. Visto a natureza NP-difícil do problema, por questões computacionais, optou-se por um método heurístico, além disso, um valor não necessariamente ótimo, que respeite as restrições deixa espaço de tempo para imprevistos no trajeto.

O método utilizado presente nesse trabalho é uma adpatação do algoritmo de Dijkstra:
- Dado um grafo, passado por lista de arestas, um ponto inicial, um ponto final e os limitantes, o algoritmo percorre o grafo buscando maximizar as arestas percorridas.
- O algoritmo faz as atualizações similar ao algoritmo tradicional de Dijkstra
- Em cada etapa o algoritmo calcula o vetor com os pesos acumulados e compara com os limites pré-estabelecidos a fim de analisar a viabilidade daquele caminho.
- O algoritmo segue até encontrar o caminho com o maior número de arestas que respeite as restrições estabelecidas
- Ao final é retornado:
    - o caminho entre os vértices;
    - o custo financeiro do caminho;
    - o tempo de percurso;
    - o nível médio esperado de satisfação do viajante com aquela rota;

Escolhendo os vértices Hotel e Restaurante Spesso como vértices inicial e final, respectivamente. Removemos todas as arestas do grafo que ligam esses pontos, assim como todas as arestas com destino Hotel e como origem Restaurante Spesso, dessa forma transformamos ambos em uma fonte e um sumidouro, respectivamente. Os parâmetros limitantes foram estabelecidos como:
- *t<sub>máx</sub>* é o intervalo de tempo das 7:00 até as 13:00, contabilizando 6 horas totais, ou 360 minutos
- *c<sub>máx</sub>* é um orçamento de R$200 reais para esse percurso
- *s<sub>máx</sub>* é o complemento de satisfação mínima desejada, definido como $0.25$ ou como uma satisfação mínima de $ 75$%

In [18]:
inicio = 'Hotel' #define o ponto inicial
fim = 'Restaurante Spesso' #define o ponto final
t_max = 360  # Limite de tempo, iniciando as 7h da manhã e chegando no ultimo ponto o mais próximo das 13h
c_max = 200  # Limite de custo em reais para translado e custear os passeios
s_max = 0.25  # Limite de satisfação (média dos scores) - complementar da satisfação esperada

#função para calcular o maior percurso entre os dois vertices
caminho_1, num_arestas_1, tempo_1, custo_1, satisfacao_1 = max_vertex(
    arestas, inicio, fim, t_max, c_max, s_max
)

satisfacao_1 = (1-satisfacao_1)*100

print("Caminho:", " -> ".join(f"{p}" for p in caminho_1))
print("Número de arestas percorridas:", num_arestas_1)
print("Tempo total: {:.2f} min".format(tempo_1))
print("Custo total: R$ {:.2f}".format(custo_1))
print("Satisfação média: {:.2f}%".format(satisfacao_1))

Caminho: Hotel -> Museu do Amanhã -> Theatro Municipal -> Mosteiro de São Bento -> Restaurante Spesso
Número de arestas percorridas: 4
Tempo total: 339.78 min
Custo total: R$ 122.20
Satisfação média: 82.50%

In [19]:
# Subdividir a lista caminhos_1 em duas
caminhos_sem_hotel = [ponto for ponto in caminho_1 if ponto != 'Hotel']
caminhos_sem_spesso = [ponto for ponto in caminho_1 if ponto != 'Restaurante Spesso']

print("Lista sem 'Hotel':", caminhos_sem_hotel)
print("Lista sem 'Restaurante Spesso':", caminhos_sem_spesso)

Lista sem 'Hotel': ['Museu do Amanhã', 'Theatro Municipal', 'Mosteiro de São Bento', 'Restaurante Spesso']
Lista sem 'Restaurante Spesso': ['Hotel', 'Museu do Amanhã', 'Theatro Municipal', 'Mosteiro de São Bento']

In [ ]:
# Filtrar a coluna destino com os valores presentes na lista 'caminhos_sem_hotel'
df_filtrado_destino = df[df['destino'].isin(caminhos_sem_hotel)]

# Filtrar a coluna origem com os valores presentes na lista 'caminhos_sem_spesso'
df_filtrado_origem = df[df['origem'].isin(caminhos_sem_spesso)]

In [20]:
# Filtrar o DataFrame para manter apenas as linhas que atendem ambas as condições
df_final = df[(df['destino'].isin(caminhos_sem_hotel)) & (df['origem'].isin(caminhos_sem_spesso))]

# Exibir o DataFrame final
print("DataFrame final após aplicar as restrições:")
df_final

DataFrame final após aplicar as restrições:

,origem,destino,score_passeio,custo_total,tempo_total
3,Hotel,Museu do Amanhã,0.15,30.0,121.466667
6,Hotel,Theatro Municipal,0.15,20.0,94.016667
8,Hotel,Mosteiro de São Bento,0.30,0.0,54.816667
62,Museu do Amanhã,Theatro Municipal,0.15,20.0,116.683333
64,Museu do Amanhã,Mosteiro de São Bento,0.30,0.0,38.783333
69,Museu do Amanhã,Restaurante Spesso,0.10,76.5,59.150000
102,Theatro Municipal,Museu do Amanhã,0.15,30.0,116.500000
106,Theatro Municipal,Mosteiro de São Bento,0.30,0.0,49.850000
111,Theatro Municipal,Restaurante Spesso,0.10,75.4,20.000000
130,Mosteiro de São Bento,Museu do Amanhã,0.15,30.0,98.600000
133,Mosteiro de São Bento,Theatro Municipal,0.15,20.0,109.916667
139,Mosteiro de São Bento,Restaurante Spesso,0.10,72.2,51.783333


Os resultados obtidos com esses parâmetros forma uma rota percorrendo quatro arestas, ou, 5 vértices com um custo de R$ $122,20$, gastando um total de $331,78$ minutos, ou, aproximadamente 5h30min com uma satisfação média e $82,5$%.

É possível alterar os valores obtidos alterando os limites das restrições afim de obter outras combinações de caminhos